config:
  # 是否开启 swagger
  swaggerEnabled: true
  # 本地文件路径
  localPath: /Users/vjf/Projects/idea/logs/base-end
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 密码
    password: 123456
    # 数据库索引
    database: 0
    # 端口，默认为6379
    port: 6379
  datasource:
    oracle:
      password: oracle
      url: localhost
      port: 1521
      username: oracle
      serviceName: ORCL
      schema: test
    # PostgreSQL数据源配置
    postgres:
      url: localhost
      port: 5432
      database: customer360
      username: postgres
      password: postgres